### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by BallisticPain** [milesj/type-converter#4]
@milesj If this project is deprecated, is there a better or newer solution, or it's simply deprecated due to you no longer intend to maintain it?

Thanks!
Jarvis

**Comment by milesj** [comment]
It's more of the latter. I no longer work in PHP and haven't touched this code base in years.

I don't know of another third-party replacement, but I was working on a replacement in my Titon project here: https://github.com/titon/utility-old/blob/master/src/Titon/Utility/Converter.php It's still a bit out of date though.

But simply don't have time for them anymore.

**Comment by BallisticPain** [comment]
Thanks for letting me know! The xmlToArray is working well for me. 

Appreciate your past hard work!

What are you into these days? Looks like frontend/JavaScript/TypeScript/React? (I checked out titon.io)

I'm a backend guy, but have been peeking at Angular, TypeScript, and a relatively new cross-platform framework for mobile development called NativeScript.

Wish you all the best in your endeavors!
Jarvis

**Comment by milesj** [comment]
My current job is primarily in the front-end stack. Node, React, Redux, Babel, Flow, TypeScript, etc. The JS world has gotten much better the past few years.

I do dabble in some Ruby and Java here and there.
